# Site settings
title: Laura's First Git Page!
author:Laura Loughmiller
  name: Laura Loughmiller
  email: laurajones2@fakeemail.com
description: "This took me longer than it should have"

# Build settings
remote_theme: jekyll/minima
